name: Build and deploy dotnet core project to Azure Function App - GSRSensorApi

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'    # path to your Function project
  DOTNET_VERSION: '9.0.x'                # semver, include‑prerelease if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true

      - name: Restore & Publish
        run: |
          dotnet restore ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          dotnet publish ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} \
            --configuration Release \
            --output ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          auth-type: SERVICE_PRINCIPAL
          creds:    ${{ secrets.AZURE_CREDENTIALS }}

      - name: Zip the published output
        run: |
          zip -r package.zip ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/publish

      - name: Deploy via Azure CLI (run‑from‑zip)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az functionapp deployment source config-zip \
              --resource-group ${{ secrets.AZURE_FUNCTIONAPP_RESOURCE_GROUP }} \
              --name gsrsensorapi \
              --src package.zip
