name: Build and deploy dotnet core project to Azure Function App - GSRSensorApi

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # path to your Function project
  DOTNET_VERSION: '9.0.x'              # semver format, include prerelease if you’re on preview

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }} SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true

      - name: Restore & publish
        run: |
          pushd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          dotnet restore
          dotnet publish --configuration Release --output ./publish
          popd

      - name: Deploy to Azure Functions (via publish profile ZIP‑deploy)
        uses: Azure/functions-action@v1
        with:
          # <-- replace this secret with the XML you downloaded from:
          # Azure Portal ▸ Function App ▸ Get Publish Profile
          publish-profile: ${{ secrets.GSRSENSORAPI_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/publish'
