name: Build and deploy dotnet core project to Azure Function App - GSRSensorApi

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'    # path to your Function project
  DOTNET_VERSION: '9.0.x'                # semver format, include prerelease

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # for OIDC login
      contents: read     # for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true

      - name: Restore & build
        run: |
          pushd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          dotnet restore
          dotnet build --configuration Release --output ./publish
          popd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          auth-type: SERVICE_PRINCIPAL

      - name: Deploy to Azure Functions (ZIP)
        uses: Azure/functions-action@v1
        with:
          app-name:      'gsrsensorapi'                  # must be lowercase
          slot-name:     'Production'
          package:       '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/publish'
          publish-method: zipdeploy
